apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-stress-test-script
  namespace: default
data:
  stress-test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    // 스트레스 테스트 - 노드 오토스케일링 유발용
    export let options = {
      stages: [
        { duration: '1m', target: 50 },    // 1분 동안 50 사용자로 증가
        { duration: '3m', target: 100 },   // 3분 동안 100 사용자로 증가
        { duration: '5m', target: 200 },   // 5분 동안 200 사용자로 증가 (노드 스케일링 유발)
        { duration: '10m', target: 200 },  // 10분 동안 200 사용자 유지
        { duration: '5m', target: 100 },   // 5분 동안 100 사용자로 감소
        { duration: '3m', target: 0 },     // 3분 동안 0으로 감소
      ],
      thresholds: {
        http_req_duration: ['p(95)<5000'],
        http_req_failed: ['rate<0.2'],
      },
    };

    const BASE_URL = 'http://test-app-service.default.svc.cluster.local';

    export default function () {
      // 더 많은 요청으로 CPU 사용량 증가
      for (let i = 0; i < 5; i++) {
        let response = http.get(`${BASE_URL}/`);
        check(response, {
          'status is 200': (r) => r.status === 200,
        });
      }

      sleep(0.5); // 더 짧은 대기 시간으로 부하 증가
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-stress-test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run", "/scripts/stress-test.js"]
        volumeMounts:
        - name: k6-script-volume
          mountPath: /scripts
      volumes:
      - name: k6-script-volume
        configMap:
          name: k6-stress-test-script
      restartPolicy: Never
  backoffLimit: 1